### ISSUE TITLE
Empty breadcrumbs

### ISSUE THREAD

**Issue by afbora** [dwightwatson/breadcrumbs#10]
**/routes/web.php**

````php
Route::get('/test', 'TestController@index')->name('test');

// Breadcrumbs
Breadcrumbs::for('test', function ($trail) {
    $trail->add('Test', route('test'));
});

````

**/resources/views/vendor/breadcrumbs/bootstrap3.blade.php**

````php
{{ $breadcrumbs->count() }}
````

Frankly, I haven't been able to run this plugin successfully yet.
When i enter `/test` url, i always count as `0` zero.

`$this->route` always comes null when I check. Where am I doing wrong?
https://github.com/dwightwatson/breadcrumbs/blob/1.1.0/src/Breadcrumbs/Generator.php#L65

**Comment by dwightwatson** [comment]
I started playing around with this package recently to start work on a 2.0 version and I noticed a similar issue. I think a more recent version of Laravel has broken the route being made available. Happy to look at any PR that can resolve it, otherwise I hope to sort it out in a following version when I get time to finish it.

**Comment by afbora** [comment]
I have fixed it (about calling/binding `$router->current()` later) but `dev-master` version (instead of 1.1.0) already works great. Thanks!

**Comment by limsocheat** [comment]
{!!  Breadcrumbs::render() !!} not working on Laravel 7.
